spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: sys as sysdba
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    password: Lsnworks@1
  application:
    name: springBootTutorial
  sql:
    init:
      platform: oracle
  jpa:
    hibernate:
      ddl-auto: update
welcome:
  message: Welcome to New Day!

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        exclude: "env, beans"
